<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SarthakThinkpad" failures="1" tests="5" name="com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest" time="50.636" errors="0" timestamp="09 Apr 2023 15:37:53 GMT" skipped="3">
  <testcase classname="com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest" name="rediffLoginTest" time="9.945">
    <skipped/>
  </testcase> <!-- rediffLoginTest -->
  <testcase classname="com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest" name="rediffLoginTest" time="11.395">
    <skipped/>
  </testcase> <!-- rediffLoginTest -->
  <testcase classname="com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest" name="TNLoginTest" time="9.146"/>
  <testcase classname="com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest" name="rediffLoginTest" time="9.879">
    <skipped/>
  </testcase> <!-- rediffLoginTest -->
  <testcase classname="com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest" name="rediffLoginTest" time="10.271">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest.rediffLoginTest(TnRediffTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- rediffLoginTest -->
</testsuite> <!-- com.testngcode_9thApr_2023_Retry_Failed_TestCases.TnRediffTest -->
